name: Build, Scan and Push Docker Image


on: 
    push:
        branches: [ main ]

jobs:
    buildscanpush:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: set up java env
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Compile Java Application
          run: javac notes_app.java

        - name: sonarqube scan
          uses: sonarsource/sonarcloud-github-action@master
          timeout-minutes: 5
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
            
        - name: Log in to Docker Hub
          if: success()
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        # 7. Build and Push Docker Image
        - name: Build and Push
          if: success()
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/bad-notes-app:latest

